#!/usr/bin/env bash
# portal-test.sh - does the desktop offer to open the hub's page by itself?
# Version: 1.0.0 - updated 26-09-07-13-05
#
# THE PROBLEM THIS SOLVES
# A desktop only asks "Sign in to this network" when it believes it has no
# internet. While wifi is up and working, NetworkManager reports "full" and the
# question is never asked, so the prompt can never appear. Testing it properly
# means switching wifi OFF and leaving the cable as the only link.
#
# That deliberately cuts the connection of whoever is running this test.
#
# SO: the restore is armed BEFORE anything is switched off. Two independent
# detached timers bring wifi back, neither of which depends on this script, this
# shell, or this session surviving. If everything above them dies, wifi still
# comes back.
#
# Usage:
#   ./portal-test.sh                 default 75-second dark window
#   ./portal-test.sh --window 120    longer look
#   ./portal-test.sh --dry-run       arm and verify the timers, switch nothing off

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESULTS="$HERE/results"
STAMP="$(date '+%y-%m-%d-%H-%M')"
LOG="$RESULTS/portal-$STAMP.log"
VERDICT="$RESULTS/portal-verdict-$STAMP.txt"
mkdir -p "$RESULTS"

WINDOW=75
DRY_RUN=0
while [ $# -gt 0 ]; do
    case "$1" in
        --window) WINDOW="$2"; shift 2 ;;
        --dry-run) DRY_RUN=1; shift ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

say() { printf '%s  %s\n' "$(date '+%H:%M:%S')" "$*" | tee -a "$LOG"; }

WIFI_DEV="$(nmcli -t -f DEVICE,TYPE,STATE device | awk -F: '$2=="wifi" && $3=="connected" {print $1; exit}')"
WIFI_CON="$(nmcli -t -f DEVICE,TYPE,STATE,CONNECTION device | awk -F: '$2=="wifi" && $3=="connected" {print $4; exit}')"
CABLE_DEV="$(for d in /sys/class/net/*/; do n=$(basename "$d"); [ "$n" = lo ] && continue
             [ -e "$d/wireless" ] && continue
             [ "$(cat "$d/carrier" 2>/dev/null)" = 1 ] && { echo "$n"; break; }; done)"

# The restore timers below are armed before anything is switched off and fire
# whatever happens, which is the important half. This trap is the other half:
# the things that are merely untidy if the script is interrupted, rather than
# dangerous. It must not decide anything based on whether the test succeeded.
DBUS_PID=""
WATCHDOG_WAS_UP=0
cleanup() {
    [ -n "$DBUS_PID" ] && kill "$DBUS_PID" 2>/dev/null
    # Bring wifi back here too rather than trusting the timers alone. They are
    # the belt; this is the one that runs immediately on a ctrl-c.
    nmcli radio wifi on >/dev/null 2>&1
    nmcli device connect "$WIFI_DEV" >/dev/null 2>&1 \
        || nmcli connection up "$WIFI_CON" >/dev/null 2>&1
    [ "$WATCHDOG_WAS_UP" = 1 ] && "$HERE/network-watchdog.sh" start --lifetime 600 >/dev/null 2>&1
    true
}
trap cleanup EXIT INT TERM

say "captive-portal-test  window=${WINDOW}s  wifi=$WIFI_DEV/'$WIFI_CON'  cable=${CABLE_DEV:-none}"

if [ -z "$WIFI_DEV" ] || [ -z "$WIFI_CON" ]; then
    say "ABORT: no connected wifi to restore afterwards. Refusing to switch anything off."
    exit 1
fi
if [ -z "$CABLE_DEV" ]; then
    say "ABORT: no cable with carrier. Without it, switching wifi off leaves no network at all."
    exit 1
fi

# ---------------------------------------------------------------- arm restore
# Written to a standalone file so the timers do not depend on this script.
RESTORE="$RESULTS/restore-wifi-$STAMP.sh"
cat > "$RESTORE" <<RESTORE_EOF
#!/usr/bin/env bash
# Generated by portal-test.sh. Single job: put wifi back. Runs detached.
sleep "\$1"
for attempt in 1 2 3 4 5; do
    nmcli radio wifi on 2>/dev/null
    nmcli device connect "$WIFI_DEV" 2>/dev/null || nmcli connection up "$WIFI_CON" 2>/dev/null
    sleep 5
    if nmcli -t -f DEVICE,STATE device | grep -q "^$WIFI_DEV:connected\$"; then
        echo "\$(date '+%H:%M:%S')  restore(\$1s): wifi back on attempt \$attempt" >> "$LOG"
        exit 0
    fi
done
echo "\$(date '+%H:%M:%S')  restore(\$1s): FAILED after 5 attempts" >> "$LOG"
RESTORE_EOF
chmod +x "$RESTORE"

# A restore timer left pending from an EARLIER run will fire in the middle of
# this one and switch wifi back on mid-test. That happened on 2026-09-07: the
# backstop from the 12:50 run fired at 12:53:47, 57s into the 12:52 run.
STALE="$(pgrep -f 'restore-wifi-.*\.sh' | tr '\n' ' ')"
if [ -n "$STALE" ]; then
    say "killing stale restore timers from an earlier run: $STALE"
    pkill -f 'restore-wifi-.*\.sh'
    sleep 1
fi

say "arming restore timers BEFORE switching anything off"
setsid nohup "$RESTORE" "$WINDOW"            >/dev/null 2>&1 & PRIMARY=$!
setsid nohup "$RESTORE" "$((WINDOW + 120))"  >/dev/null 2>&1 & BACKSTOP=$!
sleep 1
if kill -0 "$PRIMARY" 2>/dev/null || kill -0 "$BACKSTOP" 2>/dev/null; then
    say "VERIFIED: restore armed at ${WINDOW}s (pid $PRIMARY) and $((WINDOW+120))s (pid $BACKSTOP)"
else
    say "ABORT: restore timers did not start. Switching nothing off."
    exit 1
fi

if [ "$DRY_RUN" = "1" ]; then
    say "dry run: timers armed and verified, nothing switched off. Cleaning up."
    kill "$PRIMARY" "$BACKSTOP" 2>/dev/null
    say "dry run complete"
    exit 0
fi

# The watchdog restores wifi on sight, which would end this test in 20 seconds.
# Stand it down for the duration; the two timers above are the safety net now.
if "$HERE/network-watchdog.sh" is-running; then
    say "standing the watchdog down for the duration (it would undo this test)"
    "$HERE/network-watchdog.sh" stop >>"$LOG" 2>&1
    WATCHDOG_WAS_UP=1
fi

# ---------------------------------------------------------------- capture
NOTIFY_LOG="$RESULTS/portal-notifications-$STAMP.txt"
DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$(id -u)/bus}" \
  timeout $((WINDOW + 20)) dbus-monitor --session \
  "interface='org.freedesktop.Notifications',member='Notify'" > "$NOTIFY_LOG" 2>&1 &
DBUS_PID=$!
say "watching the session bus for desktop notifications"

ps -eo comm= | sort -u > "$RESULTS/.procs-before-$STAMP"
JOURNAL_SINCE="$(date '+%Y-%m-%d %H:%M:%S')"

# ---------------------------------------------------------------- go dark
say ">>> switching wifi OFF. Cable is now the only link. Restore is armed."
nmcli device disconnect "$WIFI_DEV" >>"$LOG" 2>&1
say "wifi disconnected"

SAW_PORTAL=0
END=$(( $(date +%s) + WINDOW ))
while [ "$(date +%s)" -lt "$END" ]; do
    OVERALL="$(timeout 10 nmcli networking connectivity check 2>/dev/null)"
    PERDEV="$(nmcli -t -f DEVICE,STATE,IP4-CONNECTIVITY device status 2>/dev/null | tr '\n' ' ')"
    say "  connectivity=$OVERALL | $PERDEV"
    case "$OVERALL$PERDEV" in *portal*) SAW_PORTAL=1; say "  *** PORTAL DETECTED ***" ;; esac
    sleep 8
done

# ---------------------------------------------------------------- back up
say "<<< window over, bringing wifi back now (not waiting for the timer)"
nmcli radio wifi on >>"$LOG" 2>&1
nmcli device connect "$WIFI_DEV" >>"$LOG" 2>&1 || nmcli connection up "$WIFI_CON" >>"$LOG" 2>&1
for i in $(seq 1 12); do
    nmcli -t -f DEVICE,STATE device | grep -q "^$WIFI_DEV:connected$" && break
    sleep 3
done
kill "$DBUS_PID" 2>/dev/null

if nmcli -t -f DEVICE,STATE device | grep -q "^$WIFI_DEV:connected$"; then
    say "wifi is back: $(ip route show default | head -1)"
else
    say "wifi NOT back yet - the armed timers are still pending and will keep trying"
fi
[ "$WATCHDOG_WAS_UP" = "1" ] && "$HERE/network-watchdog.sh" start --lifetime 600 >>"$LOG" 2>&1

# ---------------------------------------------------------------- evidence
ps -eo comm= | sort -u > "$RESULTS/.procs-after-$STAMP"
NEWPROCS="$(comm -13 "$RESULTS/.procs-before-$STAMP" "$RESULTS/.procs-after-$STAMP" | tr '\n' ' ')"
journalctl --since "$JOURNAL_SINCE" --no-pager 2>/dev/null \
  | grep -iE "nmcheck|connectivity|portal|captive|NetworkManager" \
  > "$RESULTS/portal-journal-$STAMP.txt"

NOTIFY_HITS="$(grep -c 'member=Notify' "$NOTIFY_LOG" 2>/dev/null)"; NOTIFY_HITS="${NOTIFY_HITS:-0}"

{
echo "PORTAL TEST VERDICT   $STAMP"
echo "window: ${WINDOW}s with wifi off and the cable as the only link"
echo ""
echo "NetworkManager saw a portal:      $([ "$SAW_PORTAL" = 1 ] && echo YES || echo NO)"
echo "desktop notifications during test: $NOTIFY_HITS"
echo "new processes appeared:            ${NEWPROCS:-none}"
echo ""
echo "Read these for detail:"
echo "  $(basename "$LOG")"
echo "  $(basename "$NOTIFY_LOG")"
echo "  portal-journal-$STAMP.txt"
} > "$VERDICT"

rm -f "$RESULTS/.procs-before-$STAMP" "$RESULTS/.procs-after-$STAMP"
say "verdict written to $(basename "$VERDICT")"
cat "$VERDICT" | tee -a "$LOG"
